const INCREMENT = 'INCREMENT';
const DECREMENT = 'DECREMENT';
const THUNKINCREMENT = 'THUNKINCREMENT';

const ADD_TODO = 'ADD_TODO';
const DEL_TODO = 'DEL_TODO';
const TOGGLE_TODO = 'TOGGLE_TODO';
const SWITCH_TYPE = 'SWITCH_TYPE';

export {
  INCREMENT,
  DECREMENT,
  THUNKINCREMENT,
  ADD_TODO,
  DEL_TODO,
  TOGGLE_TODO,
  SWITCH_TYPE
}